services:
  mongo:
    image: mongo:7
    container_name: quynhphu-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - quynhphu_mongo_data:/data/db

volumes:
  quynhphu_mongo_data:
